# Generated by Django 4.0.4 on 2022-07-06 00:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pub_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='This is created at', verbose_name='This is Added at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Modified at', verbose_name='Modified at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', help_text='Book', max_length=1000, unique=True, verbose_name='Book')),
                ('added_by_user', models.ForeignKey(default='', help_text='Added by user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', related_query_name='books', to=settings.AUTH_USER_MODEL, verbose_name='Added by user')),
                ('author', models.ForeignKey(blank=True, default='', help_text='Author', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', related_query_name='books', to='pub_auth.author', verbose_name='Author')),
                ('publisher', models.ForeignKey(blank=True, default='', help_text='Publisher of the book', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', related_query_name='books', to='pub_auth.publisher', verbose_name='Publisher')),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'Book',
            },
        ),
    ]
