# Generated by Django 4.0.4 on 2022-07-06 01:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='subscribers',
            field=models.ManyToManyField(blank=True, help_text='List of users who have included this book in their inventory.', null=True, related_name='books_in_inventory', related_query_name='books_in_inventory', to=settings.AUTH_USER_MODEL, verbose_name='Subscribers'),
        ),
        migrations.AlterField(
            model_name='book',
            name='added_by_user',
            field=models.ForeignKey(default='', help_text='Added by user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books_added', related_query_name='books_added', to=settings.AUTH_USER_MODEL, verbose_name='Added by user'),
        ),
    ]
