# Generated by Django 4.0.4 on 2022-07-05 23:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='This is created at', verbose_name='This is Added at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Modified at', verbose_name='Modified at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Author', max_length=100, verbose_name='Author')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
                'db_table': 'Author',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='This is created at', verbose_name='This is Added at')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='Modified at', verbose_name='Modified at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Publisher's Name", max_length=100, verbose_name="Publisher's Name")),
            ],
            options={
                'verbose_name': 'Publisher',
                'verbose_name_plural': 'Publishers',
                'db_table': 'Publisher',
            },
        ),
    ]
